// 200 authored, activity-specific additions to Mom’s original dialogue.
export const momDialogue = {
  resting: [
    "Come sit with me, love. You do not have to keep busy all the time.",
    "I am having a slow day. Tell me something from your walk.",
    "Could you stay a minute? I like having you nearby.",
    "My body wants a quiet afternoon. My ears still work, though.",
    "I wish I had more energy today. I am glad to see you.",
    "I need a little rest. How are you doing, sweetheart?",
    "You do not have to whisper. I am tired, not asleep.",
    "The couch is my headquarters today.",
    "I have not got much energy, but I can listen.",
    "Let me catch my breath a moment, love.",
    "I am comfortable here. Come tell me about town.",
    "I wanted to get more done. Some days go like this.",
    "It is a resting day for me. You can put your feet up too.",
    "I am glad you came in to check on me.",
    "I need to take things slowly. That is frustrating sometimes.",
    "I am not up to much today. We can still keep each other company.",
    "Do not feel you have to make me better by yourself.",
    "I am tired, sweetheart. A little company would be lovely.",
    "You can tell me the long version. I am not going anywhere just now.",
    "Have you had a chance to rest your own legs?",
    "I would rather hear about you than stare at the television.",
    "Come closer. I do not want to miss what you are saying.",
    "I am worn out today. It helps when the house does not feel empty.",
    "You can sit without finding something to say.",
    "I wish I could be out with you. Tell me what it is like today.",
    "Some days I need more help. That is all right.",
    "I will let you know if I need something. You can breathe, love.",
    "I am trying to be patient with myself today.",
    "I know this is hard on you too.",
    "You do not need to look cheerful just for me.",
    "It is okay to tell me if you are worried.",
    "I am glad we can talk, even on a tired day.",
    "I could use a quiet minute with my favorite person.",
    "Come lean against the cushion. There is room.",
    "You have been doing a lot. Do not forget you are allowed to stop.",
    "I would like to be up. Today I need to stay here.",
    "A slow day is still a day we can spend together.",
    "I am tired enough that the television is doing most of the talking.",
    "It is nice hearing your footsteps coming home.",
    "I appreciate you checking in, sweetheart.",
    "You do not have to solve anything before you sit down.",
    "I am not feeling very lively. Tell me about something you noticed.",
    "We can be quiet together if you like.",
    "I need a bit of time before I try getting up.",
    "I am glad you are here. That is what I wanted to say.",
    "I wish today was easier for both of us.",
    "You can ask me how I feel. I will try to tell you honestly.",
    "I am resting my body, not giving up on the day.",
    "Thank you for being gentle with me, love.",
    "We can take this afternoon a little at a time.",
  ],
  cooking: [
    "Will you pass me the spoon, sweetheart?",
    "I am glad I felt up to being in the kitchen.",
    "Something warm sounded good today.",
    "Come keep me company while I cook.",
    "Could you help me clear a little space?",
    "I like having something useful to do with my hands.",
    "We can make this together if you want.",
    "The kitchen feels nicer with you in it.",
    "I might need to sit down in a bit. For now this feels good.",
    "You can tell me about town while I work.",
    "Cooking gives the afternoon a bit of shape.",
    "Could you check whether the table is clear?",
    "I am taking my time. There is no prize for rushing dinner.",
    "I would like your company more than your kitchen skills.",
    "If you want to learn, start by watching. I can explain.",
    "I like being able to do this for us today.",
    "Remind me to rest when we are finished, love.",
    "You do not have to wait until dinner to talk to me.",
    "A little help with the washing up would be lovely.",
    "I am glad to be doing something ordinary.",
    "Will you bring a chair over? I can work sitting down too.",
    "You are welcome in my kitchen, even with muddy shoes. Wipe them first.",
    "It feels good to have a little energy to use.",
    "I do not need a fancy meal. I want us to eat together.",
    "We can keep dinner simple today.",
    "What sounds good to you? I want your opinion.",
    "You can be my helper if you are not too tired.",
    "I like when we talk while we are making things.",
    "I will save some energy for sitting with you afterward.",
    "Being up today feels good. I am trying not to overdo it.",
  ],
  birdhouses: [
    "Do you think a bird will like this little house?",
    "I am working on the roof. It needs to keep the rain out.",
    "Would you help me choose a color?",
    "I like making something with a proper little door.",
    "Hold this steady for me, love.",
    "We can hang it somewhere we can see from the window.",
    "I wonder which bird will inspect it first.",
    "A small house still needs careful work.",
    "I am glad my hands feel up to this today.",
    "Come look. What would you change?",
    "I would like to make another when I have the energy.",
    "Maybe the birds will be less fussy than we are.",
    "Could you pass me that piece of wood?",
    "I want this roof to sit straight.",
    "We should leave the entrance clear for them.",
    "You could paint a little pattern on the side.",
    "It feels good to build something again.",
    "I will take a break before I start the next piece.",
    "We do not have to finish it today.",
    "I like imagining a nest in there.",
    "Would you help me find a good place to hang this?",
    "A crooked wall might be charming. A leaky roof would not.",
    "I need to measure this one more time.",
    "We can make a tiny porch if you think it needs one.",
    "The birds get the final say, I suppose.",
    "Come sit beside me while I work on this.",
    "I like having a project we can talk about.",
    "I hope we get to see who moves in.",
    "We can keep the leftover wood for another day.",
    "Thank you for helping me with something I enjoy.",
  ],
  painting: [
    "Come look at this color. What do you think?",
    "I felt like painting something bright today.",
    "I am glad I could get my paints out.",
    "You can sit with me. You do not need to be quiet.",
    "Maybe this corner needs a little more yellow.",
    "I like being able to make a mess for a good reason.",
    "Would you help me rinse a brush?",
    "I have not decided what this picture needs yet.",
    "You are allowed to have a different opinion from mine.",
    "I can take my time with it.",
    "What would you paint if you had the brush?",
    "I like watching a picture change as I work.",
    "This part is not finished. That is okay.",
    "Come closer so you can see the little details.",
    "I think I will leave that bit alone for a moment.",
    "We could paint together another time.",
    "I want to use my energy on something I like today.",
    "There is no need for it to turn out perfect.",
    "I might stop before I get tired of it.",
    "Sometimes a different color is all a picture needs.",
    "Would you choose the next color for me?",
    "I can always paint over a mistake.",
    "I like having you nearby while I do this.",
    "Maybe I will try a smaller picture next.",
    "I am going to sit back and look at it for a minute.",
    "You can tell me what it reminds you of.",
    "I have missed making things like this.",
    "I am happy to explain what I am trying to do.",
    "Thank you for coming to see my work.",
    "I will put the brushes away when I need a rest.",
  ],
  reading: [
    "I am enjoying my book today.",
    "Let me finish this line, then tell me about your walk.",
    "Would you like to sit here and read too?",
    "I like a story that makes me want one more page.",
    "My book is keeping me company. You are welcome too.",
    "I am giving my body a rest and my mind something to do.",
    "I do not mind being interrupted by you.",
    "We could read a little together if you like.",
    "I am trying to remember where I put my bookmark.",
    "Come sit. You can tell me what you have been doing.",
    "I like getting into a story on a quiet afternoon.",
    "Do you want me to tell you what I am reading?",
    "I should stop bending the corners of the pages.",
    "This is a nice way to use a little energy.",
    "I can put the book down for a bit.",
    "Have you found anything you want to read lately?",
    "Sometimes I read the same paragraph twice and do not notice.",
    "I think I will read a little more before I get up.",
    "We do not have to talk if you would rather sit quietly.",
    "I like having you on the other end of the couch.",
    "Could you help me find something to mark my page?",
    "I am not racing to finish it.",
    "A good book makes a quiet day feel less long.",
    "I can read a bit out loud if you want.",
    "I will not tell you the ending if you want to read it too.",
    "I am glad I can concentrate on a story today.",
    "You can ask me about it. I like talking about books.",
    "I might save the next chapter for later.",
    "Come keep me company for a page or two.",
    "I am happy with a book and a little time together.",
  ],
  garden: [
    "Those money trees are strange-looking, but thank you for your work.",
    "I am glad I could come see the garden today.",
    "You have put a lot of effort into this.",
    "The branches are rather spooky, sweetheart.",
    "Come show me what you have been doing.",
    "I like being outside with you.",
    "I might need to go in soon. I am enjoying this for now.",
    "I can see that you are taking care of things.",
    "Thank you for letting me have a look.",
    "Maybe we could grow some flowers alongside these odd trees.",
    "I will not pretend these are pretty trees. You have worked hard, though.",
    "It is nice to have something to look at outside.",
    "What is this part of the garden for?",
    "You can explain it slowly. I am still learning.",
    "I like hearing you talk about something you have made.",
    "I appreciate the work, even if the trees look like Halloween.",
    "Would you show me where you want to plant next?",
    "A few normal flowers would look cheerful here.",
    "I am glad to share a bit of your afternoon.",
    "You should rest after all that digging too.",
    "I would like to come look again when I have the energy.",
    "You have an interesting garden, that is certain.",
    "Those branches look a little alarming. Thank you for tending them.",
    "I am happy you wanted to show me around.",
    "Tell me which tree you are watching most closely.",
    "It feels good to get a little fresh air.",
    "We can walk slowly. There is no rush.",
    "I like seeing what you spend your time on.",
    "Thank you for all the care you have put in, love.",
    "Let us look a little longer before we go inside.",
  ],
} as const;
