// Whole authored lines, with different subjects rather than repeated stock closers.
export const extraTownLines: Record<string, string[]> = {
  npc1: [
    "The tulips open earlier than I do. I am not a morning person.",
    "I moved that rose three times. It finally likes the third spot.",
    "A bee landed on my sleeve. I stayed very still until it left.",
    "That pink flower is a peony. It looks like a scoop of ice cream.",
    "I leave the seed heads for the birds. They can tidy them up.",
    "These dahlias started as ugly little lumps. Look at them now.",
    "I tried a blue flowerbed. Then one orange poppy invited itself.",
    "The lavender smells best when the sun warms it.",
    "I planted those snapdragons because I like the name.",
    "My gloves have a hole. One finger gets all the gardening experience.",
    "I draw my planting plans on old envelopes. They never stay that neat.",
    "The big watering can is heavy. Two small trips are kinder to my back.",
    "I bought one packet of cosmos. Apparently that was plenty.",
    "The nasturtiums can trail over the edge. I like a messy border.",
    "I found my lost trowel under a pot. I blamed the squirrels too soon.",
    "That white daisy leans toward the lane. Very nosy flower.",
    "I save the empty pots. Somehow there are never enough in spring.",
    "I am trying not to fuss over the seedlings every five minutes.",
    "The mint stays in its own pot. It does not understand boundaries.",
    "You can smell the rain in the soil before the flowers notice.",
    "A butterfly sat on that purple bloom for ages. Good choice, really.",
    "My garden chair has more muddy handprints than the shed door.",
    "Those little violas look like faces. I count them as company.",
    "I water at the roots. Wet petals do not make a happy rose.",
  ],
  npc2: [
    "My tropical plants take up more room than my furniture.",
    "That huge leaf belongs to a monstera. The holes are supposed to be there.",
    "The banana plant is decorative. I am still buying my bananas.",
    "I mist the fern, and then I forget where I put the spray bottle.",
    "An orchid looks fancy until you see the pot I keep it in.",
    "That red bromeliad makes the whole border look warmer.",
    "I have a plant called a bird of paradise. No actual bird included.",
    "The big palm likes its sunny corner. I would too, if I fit there.",
    "I rotate the pots so they do not all lean toward the same window.",
    "A leaf unfurled this morning. It was rolled up like a tiny umbrella.",
    "I label my cuttings. Otherwise everything is just the green one.",
    "The rubber plant is real. Its name confused me for years.",
    "My watering schedule is written on the back of a cereal box.",
    "I tried an indoor jungle. The jungle seems to have won.",
    "Those ferns are older than my garden boots.",
    "The gate is quieter now. I am taking all the credit.",
    "I saw a very determined ant carrying something twice its size.",
    "The hat shop window changes more often than my curtains.",
    "I keep a spare latch in the shed. Finding it is the hard part.",
    "I have stopped guessing what Robertson keeps in those tins.",
    "There is a nice bit of shade just beyond that bend.",
    "My hose got a knot in it. I did not know a hose could do that.",
    "I leave a shallow dish of water out for visiting birds.",
    "I tried sitting quietly in the garden. A leaf fell right in my tea.",
  ],
  npc3: [
    "I grow carrots because pulling them up is such a nice surprise.",
    "Those climbing beans needed a taller frame than I expected.",
    "One courgette plant is enough. I learned that the hungry way.",
    "I planted radishes between the slower things. They finish first.",
    "The tomatoes need tying up again. They grow while I am not looking.",
    "I pick the peas before they get tough. Waiting is not always better.",
    "A lettuce is a very patient sort of lunch.",
    "I keep the onions in one row so I do not weed them by accident.",
    "The runner beans have red flowers. Vegetables can be pretty too.",
    "I do not plant everything on the same day. That would be a lot of soup.",
    "The cabbages look like they are keeping secrets in the middle.",
    "I found a potato in a place I never planted one.",
    "The basil goes by the tomatoes. Mostly because I like smelling it.",
    "I washed a carrot and ate it outside. That is my idea of a picnic.",
    "I mark the rows with sticks. My handwriting does not survive the rain.",
    "A pumpkin needs much more room than the seed packet admits.",
    "I put spare beans by the gate for anyone who wants them.",
    "I would rather share the extras than watch them go soft.",
    "A robin waits until I start digging. It knows what a shovel means.",
    "I keep a notebook of what grows well. Mostly it says more peas.",
    "The nasturtiums keep wandering into my vegetable rows.",
    "I checked the compost. It is doing its job very quietly.",
    "The shed smells of soil and old string. I quite like it.",
    "I forgot a basket outside. It is a flowerpot now.",
  ],
  haberdashery: [
    "Try the hats on the stands! Each has a little talent of its own. The green cap has a curious brim…",
    "Three hats is a stack. Four hats is a disagreement with the ceiling.",
    "A hat should fit your head and your plans for the afternoon.",
    "The rabbit ears have a habit of catching the doorway. Mind your head.",
    "I leave the fancy feather where the light can catch it.",
    "The propeller is balanced. I checked it with a very patient teaspoon.",
    "Buttons make fine decorations. Spare buttons make fine emergencies.",
    "A crooked brim is a decision. A loose seam is something I fix.",
    "That velvet looks different when you brush it the other way.",
    "I keep ribbons in biscuit tins. The disappointment is unavoidable.",
    "A tall hat belongs on top. It needs room to be ridiculous.",
    "There is a mirror if you want to judge your own hat situation.",
    "The little green cap looks ordinary. I would not rely on appearances.",
    "I measure twice because I am very bad at guessing.",
    "The thread always tangles when somebody is watching.",
    "I made a hat for a scarecrow once. Very easy fitting appointment.",
    "The bunny ears are hand stitched. They do not grow by themselves.",
    "Your bedroom rack is a sensible place for hats you are not wearing.",
    "I found a needle in my sleeve yesterday. That could have ended badly.",
    "Some hats are useful. Some hats are a useful sort of silly.",
    "That little whirligig needs air around it. Give it the top spot.",
    "The cheap hats get just as much care as the expensive ones.",
    "A loose feather can be fixed. A bad haircut takes longer.",
    "Please do not put a damp hat in a drawer. Let it breathe first.",
  ],
  bicycle: [
    "A good bike makes a small town feel big. We’ll have something for you soon.",
    "I can fix a wheel that wobbles. I cannot fix a rider who refuses lunch.",
    "The bell is for letting people know you are there. Not for the whole journey.",
    "I lined up the little parts, and then my elbow moved the whole system.",
    "A saddle should not feel like sitting on a fence.",
    "I like a bike with a basket. It leaves both hands for steering.",
    "That old pump makes a wonderful noise and very little air.",
    "I keep finding tyre patches in my pockets.",
    "A clean chain is quieter. Usually the rider is not.",
    "The shop smells like rubber. You stop noticing after a while.",
    "I once fixed a bike with two different-sized wheels. Interesting ride.",
    "A helmet is a much better idea than finding out the hard way.",
    "The smallest wrench is always the one I cannot find.",
    "I put a basket on a bicycle for groceries. Then I had to buy fewer melons.",
    "The shiny new spokes look nice, but straight ones are the important bit.",
    "I tighten things carefully. More force is not always more fixed.",
    "There is an old bell in the drawer that sounds like a tiny church.",
    "I would test every bike myself, but some of the seats are very small.",
    "The repair stand saves my back. Best thing in the shop.",
    "I draw little arrows on boxes so I remember which parts belong together.",
    "A puncture makes a good excuse for a slower trip home.",
    "That tyre valve cap is smaller than a pea. Easier to lose, too.",
    "I keep an old wheel by the door. People always spin it.",
    "One day I will tidy the workbench. Not today, apparently.",
  ],
  robertson: [
    "Well, look who it is! Lovely day for a little dirt under your nails.",
    "Morning, kid. I was just checking the stock behind the counter.",
    "You caught me counting screws. I will have to start over now.",
    "That bell gets a workout. Nice to see who is ringing it.",
    "The groceries go on one side, the nails on the other. Usually.",
    "I put the seed tins in order. Somebody will undo that by lunchtime.",
    "A little shop keeps you busy in a hundred little ways.",
    "The broom fell over again. It is the least reliable employee here.",
    "I found a price label on my apron. Apparently I am three dollars.",
    "There you are. Come in, mind the crates.",
    "I was looking for my pencil. It was behind my ear all along.",
    "People come in for one thing and remember three more.",
    "I keep the heavy bags down low. My knees have opinions about lifting.",
    "The grocery shelves need filling again. That is a good problem.",
    "I have had this apron longer than that doorbell.",
    "The old till likes a gentle hand. Like most old things.",
    "A fresh delivery smells of cardboard and apples.",
    "I never remember how many pegs are in a packet. I have to read it.",
    "I found a nut without its bolt. A very small mystery.",
    "Glad you stopped in. This counter is better with somebody on the other side.",
    "I label the jars carefully. Flour and plaster look too much alike.",
    "The shelves are crooked, but the prices are straight.",
    "I swept under the counter. Found enough coins for a biscuit.",
    "Take your time looking. I am not going anywhere fast.",
  ],
  "mom-out": [
    "You headed into town? OK, love you!",
    "Heading out, sweetheart? Tell me about it when you get back.",
    "Have a good walk, love. I’ll be here.",
    "Off exploring again? Love you. See you soon.",
    "Take your time crossing the lane, sweetheart.",
    "Going out? Give me a hug before you disappear.",
    "You do not have to hurry back on my account.",
    "Tell Bea I said hello if you see her.",
    "Have a look at the shop windows for me.",
    "If you find something funny, remember it so you can tell me.",
    "Come home if you get hungry. The garden can wait.",
    "I will be glad to hear about your afternoon.",
    "Do up your shoes before you go. I know, I always say that.",
    "Enjoy the fresh air for both of us.",
    "You can leave your things here until you get back.",
    "Go on, love. I know you have things you want to do.",
    "Be kind to yourself out there, all right?",
    "A little walk sounds nice. Tell me what you see.",
    "Do not worry if you take the long way home.",
    "I love you. That bit never changes.",
    "You know where I am if you need me.",
    "Take a jacket if you think you will be out late.",
    "I hope you find a nice spot to sit for a minute.",
    "See you soon, sweetheart. I am glad you are getting out.",
  ],
  "mom-home": [
    "You’re home, sweetheart.",
    "There you are! How was your walk?",
    "It’s good to see you, love.",
    "Come tell me what you found today.",
    "Hello, my love. Come sit for a little while.",
    "I heard the door. I hoped it was you.",
    "Back already? I am happy to see you.",
    "Did you take the long way round?",
    "Put your bag down. You can tell me all about it.",
    "Come here, sweetheart. I missed your face.",
    "How did things go in town?",
    "Welcome home. I like saying that.",
    "Was it nice outside?",
    "You are allowed a rest now, you know.",
    "I was wondering what you were up to.",
    "There is my favourite person.",
    "You do not need a reason to come sit with me.",
    "Did anything make you laugh today?",
    "Have you eaten something? I have to ask.",
    "Come in, love. You can take your shoes off.",
    "I am glad the door is such a short walk from your garden.",
    "I like hearing you potter about the house.",
    "We can have a quiet minute together if you like.",
    "Tell me the little things too. I want to hear them.",
  ],
};
