import { test } from "node:test";
import assert from "node:assert/strict";
import { fresh, buy, withdraw, sleep, harvest, decode } from "../src/game";
test("first night before harvest questions seeds and the housing fallback", () => {
  const s = fresh();
  withdraw(s);
  buy(s, "seeds");
  sleep(s);
  const entry = s.journal[1];
  assert(!entry.includes("—"));
  assert(entry.startsWith("Day 1\n\n"));
  assert(entry.includes("almost half my $4.33"));
  assert(entry.includes("This better work"));
  assert(entry.includes("Auntie"));
  assert(entry.includes("What on earth"));
  assert(!s.harvestReflected);
});
test("first harvested night calculates remaining surgery days once, even after day one", () => {
  const s = fresh();
  s.boughtSeeds = true;
  s.cash = 33;
  s.bank = 0;
  sleep(s);
  s.plots[0] = { stage: "ready", remaining: 0, fertilized: false, yield: 500 };
  harvest(s, 0);
  s.plots[1] = { stage: "ready", remaining: 0, fertilized: false, yield: 200 };
  harvest(s, 1);
  sleep(s);
  const entry = s.journal[2];
  assert(entry.includes("It really grew money"));
  assert(entry.includes("$7.00"));
  assert(entry.includes("$9,992.67") === false);
  assert(entry.includes("$9992.67"));
  assert(entry.includes("1,428 more days"));
  assert(s.harvestReflected);
  assert(!entry.includes("—"));
  assert(decode(JSON.stringify(s))!.harvestReflected);
  s.events.push("Harvested $7.00 from a money tree.");
  sleep(s);
  assert(!s.journal[3].includes("It really grew money"));
});
test("legacy diary pages shed em dashes and reflection flag migrates", () => {
  const legacy: any = fresh();
  delete legacy.harvestReflected;
  legacy.journal.push("Day 1 — I talked — and planted.");
  const s = decode(JSON.stringify(legacy))!;
  assert(s.journal.every((p) => !p.includes("—")));
  assert(!s.harvestReflected);
});
